#mongo variables
mongodb_backup_username: "mongodb_backup"
mongodb_backup_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34373539656462613063376236303031393830376162353133333731313531616437313662333232
          3263303062353838646431333235376665636536353562660a396430303039663636326232353135
          35383064346331663938386138383161303161646265343735336466303130386466393932623430
          6462306436343333310a643466656233633365363839323364626531623037363362333561633439
          3731
pritunl_db_uri: "mongodb://{{ mongodb_backup_username }}:{{ mongodb_backup_password }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ mongodb_users.pritunl.database }}"
mongodb_port: 27017
mongodb_host: 127.0.0.1


#cron schedule for backup and check_backup
cron_jobs:
  - job: /bin/bash /root/scripts/mongodb_backup.sh
    minute: 0
    hour: 3
    name: mongodb_backup
  - job: /bin/bash /root/scripts/check_mongodb_backup.sh
    minute: 0
    hour: 6
    name: check_mongodb_backup

#s3 credentinals
s3_bucket: "stellarcard-backups"
region: "us-east-2"
s3_path: "ops-main/mongo"

#alertmanager credentials
alertmanager_basic_auth_enabled: false
alertmanager_user: "alertmanager_user"
alertmanager_password: "alertmanager_password"
alertmanager_url: https://alertmanager.dev.stellarcard.io/api/v2/alerts

# aws cli
aws_cli_download_url: https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip

retention_policy: 30
