vault:
  server: ""
  kv_path: ""
  apiVersion: "v2"

kubernetes:
  role: ""

clusterStore:
  name: "vault-backend"

k8s_auth:
  serviceAccountName: "external-secrets"
  namespace: "external-secrets"
  audiences: []

conditions: []
