---
- name: Update apt and install packages
  become: true
  apt:
    update_cache: yes

- name: Create script directory
  file:
    path: /root/scripts
    state: directory

- name: Add backup script
  template:
    src: mongodb_backup.sh.j2
    dest: /root/scripts/mongodb_backup.sh
    mode: '755'

- name: Add check backup script
  template:
    src: check_mongodb_backup.sh.j2
    dest: /root/scripts/check_mongodb_backup.sh
    mode: '755'

- name: Add cron jobs
  cron:
    name: "{{ item.name | default('AnsibleUndefinedName ' + item.job)}}"
    user: "root"
    minute: "{{ item.minute | default('01')}}"
    hour: "{{ item.hour | default('00') }}"
    day: "{{ item.day | default('*') }}"
    weekday: "{{ item.weekday | default('*') }}"
    month: "{{ item.month | default('*') }}"
    job: "{{ item.job }}"
  loop: "{{ cron_jobs }}"
