---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterStore.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kv_path | quote }}
      version: {{ .Values.vault.apiVersion | quote }}
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.kubernetes.role | quote }}
          serviceAccountRef:
            name: {{ .Values.rbac.externalSecretsServiceAccount | quote }}
            audiences:
              {{- toYaml .Values.rbac.audiences | nindent 14 }}
            namespace: {{ .Release.Namespace | quote }}
