# https://external-secrets.io/latest/api/clustersecretstore/
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.clusterStore.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- with .Values.conditions }}
  conditions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.kv_path | quote }}
      version: {{ .Values.vault.apiVersion | quote }}
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: {{ .Values.kubernetes.role | quote }}
          serviceAccountRef:
            name: {{ .Values.k8s_auth.serviceAccountName | quote }}
            namespace: {{ .Values.k8s_auth.namespace | quote }}
            {{- with .Values.k8s_auth.audiences }}
            audiences:
              {{- toYaml . | nindent 14 }}
            {{- end }}
