{{- range $configmap, $values := .Values.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmap }}
  {{- with $values.annotations }}
  annotations:
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
  {{- range $key, $value := $values.labels }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
{{- with $values.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
